version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: REPLACE ME
    AWS_ACCOUNT_ID: REPLACE ME

phases:
  install:
    runtime-versions:
      docker: 19
      python: 3.8
    commands:
      - export DOCKER_BUILDKIT=1
      - export COMPOSE_DOCKER_CLI_BUILD=1
      - pip install taskipy
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      # https://github.com/moby/moby/issues/39003#issuecomment-852915070 - use buildkit inline cache for actual caching.
      - docker build --cache-from $AWS_FULL_IMAGE_NAME_LATEST --build-arg BUILDKIT_INLINE_CACHE=1 -t $AWS_FULL_IMAGE_NAME .
      - task ci:test

