version: "3.8"

services:
  # The general app which we've instrumented
  app:
    image: us-east1-docker.pkg.dev/mocap-test-project/jonbot/template-api
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
    ports:
      - "57000:8080"

  # For persistence
  # Even if you don't think you need it, chances are you do.
  store:
    image: library/postgres:13-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ml
    ports:
      - "56000:5432"
